import React, { useEffect, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import axios from 'axios';
import './Members.css';

const ReceiptView = () => {
  const { id } = useParams();
  const [data, setData] = useState(null);
  const [error, setError] = useState('');

  useEffect(() => {
    axios
      .get(`/api/pledges/receipts/${id}`)
      .then((r) => setData(r.data))
      .catch((e) => setError(e.response?.data?.error || 'Not found'));
  }, [id]);

  if (error) return <div className="error-message">{error}</div>;
  if (!data) return <div>Loading…</div>;

  const { receipt, church } = data;
  const brandColor = church?.primaryColor || '#1e3a5f';

  return (
    <div className="members-page">
      <div className="members-header no-print">
        <Link to="/pledges" className="btn btn-secondary">
          Back
        </Link>
        <button type="button" className="btn btn-primary" onClick={() => window.print()}>
          Print
        </button>
      </div>

      <div
        className="card"
        style={{
          borderTop: `6px solid ${brandColor}`,
          maxWidth: 640,
          margin: '0 auto'
        }}
      >
        <div style={{ display: 'flex', gap: 16, alignItems: 'center', marginBottom: 16 }}>
          {church?.logoUrl && (
            <img src={church.logoUrl} alt="" style={{ height: 56, objectFit: 'contain' }} loading="lazy" decoding="async" />
          )}
          <div>
            <h1 style={{ margin: 0, color: brandColor, fontSize: '1.5rem' }}>{church?.name || 'Church'}</h1>
            {church?.address && <p style={{ margin: '4px 0', color: '#666', fontSize: 13 }}>{church.address}</p>}
            {(church?.email || church?.phone) && (
              <p style={{ margin: 0, color: '#666', fontSize: 13 }}>
                {[church.email, church.phone].filter(Boolean).join(' · ')}
              </p>
            )}
          </div>
        </div>

        <h2 style={{ borderBottom: '1px solid #eee', paddingBottom: 8 }}>Official Receipt</h2>
        <p>
          <strong>Receipt #:</strong> {receipt.receipt_number}
        </p>
        <p>
          <strong>Date:</strong> {receipt.receipt_date}
        </p>
        <p>
          <strong>Received from:</strong> {receipt.is_anonymous ? 'Anonymous Donor' : receipt.donor_name || '—'}
        </p>
        <p>
          <strong>Amount:</strong>{' '}
          <span style={{ fontSize: '1.25rem', fontWeight: 700 }}>
            {receipt.currency} {Number(receipt.amount).toFixed(2)}
          </span>
        </p>
        <p>
          <strong>Payment method:</strong> {receipt.payment_method}
        </p>
        <p>
          <strong>For:</strong> {receipt.description || receipt.receipt_type}
        </p>
        <p style={{ marginTop: 24, fontSize: 12, color: '#888' }}>
          Thank you for your generosity. This receipt was generated by {church?.name || 'the church'}.
        </p>
      </div>
    </div>
  );
};

export default ReceiptView;
